security:

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_manager            

    encoders:
        "FOS\\UserBundle\\Model\\UserInterface": sha512
        
    firewalls:
        login_firewall:
            pattern:    ^/admin/login$
            anonymous:  ~
        
        secured_area:
            pattern: /admin(.*)
            form_login:
                check_path: /admin/login_check
                login_path: /admin/login
                provider: fos_userbundle
                # login success redirecting options (read further below)
                always_use_default_target_path: false
                default_target_path:            /admin/dashboard
                target_path_parameter:          _target_path
                use_referer:                    false
            logout:
                path: /admin/logout
                target: /
            anonymous: false
                
    access_control:
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/resetting$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       